name = "Generatingfunctionology"
defaultTargets = ["Generatingfunctionology"]

[leanOptions]
autoImplicit = false
pp.unicode.fun = true

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "Generatingfunctionology"
globs = ["Generatingfunctionology.+"]
